addon/urls.py
""" Urls dos opcionais """

from django.conf.urls import include, url
from django.views.generic import RedirectView

from addon import views


theme_urls = [
    url(
        r'^(?P<pk>[\d]+)/delete/$',
        views.ThemeDeleteView.as_view(),
        name='theme-delete'
    ),
    url(
        r'^(?P<pk>[\d]+)/edit/$',
        views.ThemeEditView.as_view(),
        name='theme-edit'
    ),
    url(
        r'^add/$',
        views.ThemeAddView.as_view(),
        name='theme-add'
    ),
    url(
        r'^$',
        views.ThemeListView.as_view(),
        name='theme-list'
    ),
]

optional_urls = [
    url(
        r'^products/(?P<optional_pk>[\d]+)/edit/$',
        views.OptionalProductEditView.as_view(),
        name='optional-product-edit'
    ),
    url(
        r'^services/(?P<optional_pk>[\d]+)/edit/$',
        views.OptionalServiceEditView.as_view(),
        name='optional-service-edit'
    ),
    url(
        r'^products/$',
        views.OptionalProductListView.as_view(),
        name='optional-product-list'
    ),
    url(
        r'^services/$',
        views.OptionalServiceListView.as_view(),
        name='optional-service-list'
    ),
    url(
        r'^products/add/$',
        views.OptionalAddProductView.as_view(),
        name='optional-product-add'
    ),
    url(
        r'^services/add/$',
        views.OptionalAddServiceView.as_view(),
        name='optional-service-add'
    ),
    url(
        r'^$',
        RedirectView.as_view(
            pattern_name='addon:optional-service-list',
            permanent=False
        )
    ),
]

urlpatterns = [
    url(r'^events/(?P<event_pk>[\d]+)/addons/', include(optional_urls)),
    url(r'^events/(?P<event_pk>[\d]+)/addons/themes/', include(
        theme_urls
    )),
]

raffle/urls.py
from django.conf.urls import include, url

from raffle import views


private_raffle_urls = [
    url(
        r'^raffles/winners/delete/$',
        views.WinnerDeleteView.as_view(),
        name='winner-delete'
    ),
    url(
        r'^raffles/(?P<pk>[\d]+)/winners/add/$',
        views.WinnerFormView.as_view(),
        name='winner-register'
    ),
    url(
        r'^raffles/(?P<pk>[\d]+)/winners/$',
        views.WinnerListView.as_view(),
        name='winner-list'
    ),
    url(
        r'^raffles/(?P<pk>[\d]+)/winners/$',
        views.WinnerListView.as_view(),
        name='winner-list'
    ),
    url(
        r'^raffle/(?P<pk>[\d]+)/delete/$',
        views.WinnerDeleteView.as_view(),
        name='raffle-delete'
    ),
    url(
        r'^raffles/(?P<pk>[\d]+)/edit/$',
        views.RaffleEditView.as_view(),
        name='raffle-edit'
    ),
    url(
        r'^raffles/(?P<pk>[\d]+)/$',
        views.RafflePanelView.as_view(),
        name='raffle-panel'
    ),
    url(
        r'^raffles/add/$',
        views.RaffleAddView.as_view(),
        name='raffle-add'
    ),
    url(
        r'^raffles/$',
        views.RaffleListView.as_view(),
        name='raffle-list'
    ),
]
urlpatterns_private_raffles = [
    url(r'^events/(?P<event_pk>[\d]+)/', include(private_raffle_urls))
]

raffle/models.py
from django.db import models

from gatheros_event.models import Event
from gatheros_subscription.models import Subscription


class Raffle(models.Model):
    class Meta:
        verbose_name_plural = 'sorteios'
        verbose_name = 'sorteio'

    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        verbose_name='evento',
        related_name='raffles'
    )

    product_name = models.CharField(
        max_length=255,
        verbose_name='nome do produto'
    )

    quantity = models.PositiveSmallIntegerField(
        verbose_name='Quantidade',
        help_text='Quantos produtos serão sorteados?',
        default=1,
    )

    winner_out = models.BooleanField(
        verbose_name='retirar ganhadores',
        help_text='Ganhadores não serão sorteados novamente.'
    )

    attended_only = models.BooleanField(
        default=True,
        verbose_name='somente presentes',
        help_text='Somente presentes (check-in) participarão do sorteio.'
    )

    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='criado em'
    )

    modified = models.DateTimeField(
        auto_now=True,
        verbose_name='modificado em'
    )


class Winner(models.Model):
    class Meta:
        verbose_name_plural = 'sorteios'
        verbose_name = 'sorteio'

    raffle = models.ForeignKey(
        Raffle,
        on_delete=models.CASCADE,
        verbose_name='sorteio',
        related_name='winners'
    )

    subscription = models.ForeignKey(
        Subscription,
        on_delete=models.CASCADE,
        verbose_name='inscrição',
        related_name='raffle_winners'
    )

    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='criado em'
    )

    modified = models.DateTimeField(
        auto_now=True,
        verbose_name='modificado em'
    )

raffle/forms.py
from django import forms

from raffle.models import Raffle, Winner


class RaffleForm(forms.ModelForm):
    class Meta:
        model = Raffle
        exclude = ('event',)

    def __init__(self, event, *args, **kwargs):
        self.event = event
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.event = self.event
        return super().save(commit)


class WinnerForm(forms.ModelForm):
    class Meta:
        model = Winner
        exclude = ('event',)
        widgets = {
            'subscription': forms.HiddenInput
        }

    def __init__(self, event, *args, **kwargs):
        self.event = event
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.event = self.event
        return super().save(commit)

attendance/views/list.py
from django.views.generic import ListView

from attendance.models import AttendanceService
from .mixins import AttendancesFeatureFlagMixin


class ManageListAttendanceView(AttendancesFeatureFlagMixin, ListView):
    model = AttendanceService
    template_name = 'attendance/manage-list-attendance.html'
    ordering = ['name']

    def get_queryset(self):
        query_set = super().get_queryset()
        return query_set.filter(event=self.event).order_by('pk')

    def get_context_data(self, **kwargs):
        # noinspection PyUnresolvedReferences
        context = super().get_context_data(**kwargs)
        context['event'] = self.event
        context['has_inside_bar'] = True
        context['active'] = 'attendance'
        context['attendance_lists'] = AttendanceService.objects.filter(
            event=self.event
        )
        context.update(self.get_event_state_context_data(self.event))
        return context

raffle/views.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic
from django.views.generic.base import ContextMixin

from gatheros_event.models import Event
from gatheros_event.views.mixins import EventDraftStateMixin, AccountMixin
from raffle import forms, models


class RaffleBaseMixin(ContextMixin, AccountMixin, EventDraftStateMixin):
    permission_denied_message = 'Você não pode realizar esta ação.'

    def __init__(self, *args, **kwargs):
        self.event = None
        super().__init__(*args, **kwargs)

    def pre_dispatch(self, request):
        response = super().pre_dispatch(request)
        self.event = get_object_or_404(
            Event,
            pk=self.kwargs.get('event_pk'),
        )

        features = self.event.feature_configuration

        if not features.feature_raffle:
            raise PermissionDenied(self.get_permission_denied_message())

        return response

    def get_permission_denied_url(self):
        return reverse(
            'event:event-panel',
            kwargs={
                'pk': self.event.pk,
            }
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_event_state_context_data(self.event))
        return context


class RaffleListView(RaffleBaseMixin, generic.ListView):
    template_name = 'raffle/raffle/list.html'
    model = models.Raffle
    event = None

    def dispatch(self, request, *args, **kwargs):
        event_pk = self.kwargs.get('event_pk')
        self.event = get_object_or_404(Event, pk=event_pk)
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(event=self.event)

    def get_context_data(self, **kwargs):
        cxt = super().get_context_data(**kwargs)
        cxt['event'] = self.event
        cxt['has_inside_bar'] = True
        cxt['active'] = 'raffles'
        return cxt


class RaffleAddView(generic.CreateView, RaffleBaseMixin):
    template_name = 'raffle/raffle/form.html'
    form_class = forms.RaffleForm

    def get_success_url(self):
        return reverse('raffle:raffle-panel', kwargs={
            'event_pk': self.event.pk,
            'pk': self.object.pk,
        })

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['event'] = self.event
        return kwargs

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(event=self.event)

    def get_context_data(self, **kwargs):
        cxt = super().get_context_data(**kwargs)
        cxt['event'] = self.event
        return cxt


class RaffleEditView(generic.UpdateView, RaffleBaseMixin):
    template_name = 'raffle/raffle/form.html'
    form_class = forms.RaffleForm
    model = forms.RaffleForm.Meta.model

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['event'] = self.event
        return kwargs

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(event=self.event)

    def get_context_data(self, **kwargs):
        cxt = super().get_context_data(**kwargs)
        cxt['event'] = self.event
        return cxt

    def get_success_url(self):
        return reverse('raffle:raffle-list', kwargs={
            'event_pk': self.event.pk,
        })


class RaffleDeleteView(generic.DeleteView, RaffleBaseMixin):
    template_name = 'raffle/raffle/delete.html'
    model = models.Raffle

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(event=self.event)

    def get_success_url(self):
        return reverse('raffle:raffle-list', kwargs={
            'event_pk': self.event.pk,
        })

    def get_context_data(self, **kwargs):
        cxt = super().get_context_data(**kwargs)
        cxt['event'] = self.event
        return cxt


class RafflePanelView(generic.DetailView, RaffleBaseMixin):
    template_name = 'raffle/raffle/panel.html'
    model = models.Raffle

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(event=self.event)

    def get_context_data(self, **kwargs):
        cxt = super().get_context_data(**kwargs)
        cxt['event'] = self.event
        cxt['subscriptions'] = self.get_subscriptions()
        return cxt

    def get_subscriptions(self):
        queryset = self.event.subscriptions.filter(
            completed=True,
            test_subscription=False,
        )
        if self.object.attended_only is True:
            queryset = queryset.filter(attended=True)

        return queryset


class WinnerListView(generic.ListView, RaffleBaseMixin):
    template_name = 'raffle/winner/list.html'
    model = models.Winner
    event = None
    raffle = None

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        pk = self.kwargs.get('pk')
        self.raffle = get_object_or_404(models.Raffle, pk=pk)
        return response

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(raffle=self.raffle)

    def get_context_data(self, **kwargs):
        cxt = super().get_context_data(**kwargs)
        cxt['event'] = self.event
        return cxt


class WinnerFormView(generic.FormView, RaffleBaseMixin):
    template_name = 'raffle/winner/form.html'
    form_class = forms.WinnerForm
    object = None

    def get_success_url(self):
        return reverse('raffle:winner-register', kwargs={
            'event_pk': self.event.pk,
            'pk': self.kwargs.get('pk'),
        })

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['event'] = self.event
        return kwargs

    def get_context_data(self, **kwargs):
        cxt = super().get_context_data(**kwargs)
        cxt['event'] = self.event
        cxt['object'] = self.object
        return cxt

    def post(self, request, *args, **kwargs):
        data = request.POST.copy()
        data['raffle'] = self.kwargs.get('pk')
        request.POST = data
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)


class WinnerDeleteView(generic.DeleteView, RaffleBaseMixin):
    model = models.Winner
    http_method_names = ['post']
    object_pk = None

    def delete(self, request, *args, **kwargs):
        self.object_pk = request.POST.get('pk')
        self.object = self.get_object()
        self.object.delete()
        return HttpResponse('')

    def get_object(self, queryset=None):
        return get_object_or_404(models.Winner, pk=self.object_pk)

    def get_success_url(self):
        return reverse('raffle:winner-list', kwargs={
            'event_pk': self.event.pk,
        })

    def get_context_data(self, **kwargs):
        cxt = super().get_context_data(**kwargs)
        cxt['event'] = self.event
        return cxt

frontend/templates/raffle/raffle/delete.html
{% extends "base/base.html" %}

{% load static %}{% load i18n static %}
{% load event_tags %}
{% block title %}Deletar sorteio | Congressy{% endblock %}
{% block page_title %}Deletar sorteio{% endblock %}

{% block content %}


    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">

                <div class="panel-body">

                    Tem certeza que deseja excluir este <strong>Sorteio</strong>?
                    <br/>
                    <br/>
                    <form method="post">
                        {% csrf_token %}
                        <div>
                            <!--suppress HtmlUnknownAttribute -->
                            <input class="btn btn-danger" type="submit"
                                   value="Sim, tenho certeza"/>
                            <a class="btn btn-default" href="{% url 'raffle:raffle-list' event.pk %}">Não, leve-me de volta</a>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </div>



{% endblock %}

frontend/templates/raffle/raffle/form.html
{% extends "base/base.html" %}
{% load static %}
{% load static i18n queryset_filter %}
{% load base_tags %}
{% load widget_tweaks %}
{% load event_tags %}
{% load form_config_tags %}

{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable">
                <button type="button" class="close"
                        data-dismiss="alert" aria-hidden="true">×
                </button>
                {{ message|get_first_item }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock messages %}

{% block title %}
    Novo Sorteio | Congressy
{% endblock %}

{% block page_title %}
    Novo Sorteio
{% endblock %}

{% block page_sub_title %}
    {{ event.name }}
{% endblock %}

{% block page_description %}{% endblock %}

{% block content %}
    <form action="" method="post" class="form-horizontal form-border" role="form" name="raffle_form">
        {% csrf_token %}

        {% if form.non_field_errors %}
            {% render_errors form.non_field_errors %}
        {% endif %}

        {% for hidden_field in form.hidden_fields %}
            {% if hidden_field.errors %}
                {% render_errors hidden_field.errors %}
            {% endif %}
            {{ hidden_field }}
        {% endfor %}

        <div class="row">
            <div class="col-lg-8 col-lg-push-2 col-xl-8 col-xl-push-2">
                <div class="buttonbar">
                    <div class="float-left">
                        <a href="{% url 'raffle:raffle-list' event.pk %}"
                           class="btn btn-primary">
                            <i class="fas fa-arrow-circle-left"></i>
                            Voltar
                        </a>
                    </div>

                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-push-2 col-xl-8 col-xl-push-2">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="panel-title">Campos Principais</div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-9">
                                        {% render_generic_field form.product_name autofocus=True %}
                                    </div>
                                    <div class="col-md-3">
                                        {% render_generic_field form.quantity %}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        {% render_switchery_field form.attended_only %}
                                    </div>
                                    <div class="col-md-6">
                                        {% render_switchery_field form.winner_out %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="buttonbar bottom">
                    <div class="float-right">
                        <a href="{% url 'raffle:raffle-list' event.pk %}" class="btn btn-danger">
                            <i class="fas fa-times-circle"></i>
                            Cancelar
                        </a>
                        <button type="submit" class="btn btn-success">
                            <i class="fa fa-save"></i>
                            Salvar
                        </button>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block scripts %}
{% endblock %}

{% block styles %}
{% endblock %}

frontend/templates/raffle/raffle/panel.html
{% extends "base/base.html" %}

{% load i18n static %}
{% load event_tags %}
{% block title %}Sorteio | Congressy{% endblock %}
{% block page_title %}
    <div style="padding-bottom:10px">Sorteio de Produto</div>
    <div style="color:#666">{{ object.product_name }}</div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'assets/js/ajax.js' %}"></script>
    <script src="{% static 'assets/js/raffle.js' %}"></script>
    <script>
    var raffle, stop_counter = false, create_event_timer = null;

    function load_winners() {
        var winners = new window.cgsy.raffle.Winners();
            winners.render(
                '{% url 'raffle:winner-list' event.pk object.pk %}',
                $('#winner-list')
            );
        create_events();
    }

    function load_form() {
        var winners = new window.cgsy.raffle.Winners();
            winners.render(
                '{% url 'raffle:winner-register' event.pk object.pk %}',
                $('#winner-form')
            );
        create_events();
    }

    function register(raffle) {
        var sub_pk = $('#id_subscription').val();
        if (!sub_pk) {
            alert('Inscrição não informada.');
            create_events();
            return;
        }

        stop_counter = true;
        $('#winner_form_button').attr('disabled', '');

        var winners = new window.cgsy.raffle.Winners();
            winners.register(
                '{% url 'raffle:winner-register' event.pk object.pk %}',
                $('#winner-form'),
                sub_pk,
                function(response) {
                    load_winners();
                    raffle.registerWinner(sub_pk);
                }
            );
        create_events();
    }

    function remove(sub_pk, winner_pk) {
        if (!sub_pk || !winner_pk) {
            alert('Inscrição não informada.');
            return;
        }

        if (!confirm('Tem certeza que deseja remover o vencedor?')) {
            return;
        }

        var winners = new window.cgsy.raffle.Winners();
            winners.delete(
                '{% url 'raffle:winner-delete' event.pk %}',
                winner_pk
            ).then(function() {
                raffle.unregisterWinner(sub_pk);
                load_winners();
            });
        create_events();
    }

    function registerTimerCounter(timer_el, ends_on, callback) {
        timer_el = $(timer_el);
        ends_on = parseInt(ends_on);

        timer_el.text(ends_on);

        if (stop_counter === true || ends_on === 0) {
            if (callback && typeof callback === 'function') {
                callback();
            }
            return;
        }

        window.setTimeout(function() {
            registerTimerCounter(timer_el, ends_on - 1, callback);
        }, 1000);
    }

    function run() {
        var raffle = new window.cgsy.raffle.Raffle();
        {% if object.winner_out is False %}
            raffle.shuffleAll();
        {% endif %}

            raffle.run($('#result'), $('#id_subscription'), $('#num_participating')).then(function() {
                $('#shuffle_button').attr('disabled', 'disabled');
                var timer = $('#register_timer');
                    timer.fadeIn();

                $('#winner_form_button').removeAttr('disabled');
{#                $('#id_subscription').attr('type', 'text');#}

                stop_counter = false;
                registerTimerCounter($('#register_timer_time'), 30, function() {
                    $('#result').html('-');
                    $('#id_subscription').val('');
                    $('#shuffle_button').removeAttr('disabled');
                    $('#winner_form_button').attr('disabled', '');
                    timer.fadeOut();
                    stop_counter = true;
                });
            });
    }

    function create_events() {
        window.clearTimeout(create_event_timer);
        create_event_timer = window.setTimeout(function() {
            $('#winner_form_button').on('click', function() { register(raffle); });
        }, 500);
    }

    $(document).ready(function() {
        window.setTimeout(function() {
            create_events();
            load_winners();
            load_form();

            raffle = new window.cgsy.raffle.Raffle();
            {% for sub in subscriptions %}
            raffle.addSubscriber('{{ sub.pk }}', '{{ sub.person.name }}');
            {% endfor %}
        }, 300);
    });
    </script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-2 col-md-2">
            <a href="{% url 'raffle:raffle-list' event.pk %}"
               class="btn btn-primary">
                <i class="fas fa-arrow-circle-left"></i>
                Produtos
            </a>
        </div>
        <div class="col-sm-10 col-md-10" >
            <button type="button" class="btn btn-primary btn-trans"
                    style="float: right"
                    onclick="location.href= '{% url 'raffle:raffle-edit' event.pk object.pk %}'">
                <i class="fas fa-pencil-alt"></i>
                Editar
            </button>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3 col-lg-3 col-xl-2">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="panel-title">Filtros:</div>
                        </div>
                        <div class="panel-body">
                            <div>
                                {% if object.attended_only %}
                                <i class="fas fa-check-circle text-success"></i>
                                {% else %}
                                <i class="fas fa-times-circle text-danger"></i>
                                {% endif %}
                                <small>Somente presentes</small>
                            </div>
                            <div>
                                {% if object.winner_out %}
                                <i class="fas fa-check-circle text-success"></i>
                                {% else %}
                                <i class="fas fa-times-circle text-danger"></i>
                                {% endif %}
                                <small>Retirar vencedores</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="panel-title">Prêmios sorteados:</div>
                        </div>
                        <div class="panel-body">
                            <div class="text-center" style="font-size: 36px">
                                <span id="num_shuffled">1</span>/<span>{{ object.quantity }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-9 col-lg-9 col-xl-10">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">Realizar Sorteio</div>
                </div>
                <div class="panel-body text-center">
                    <div style="padding: 10px 0"><span class="text-bold" id="num_participating">{{ subscriptions|length }}</span> participando.</div>
                    <div>
                        <button type="button" class="btn btn-info" id="shuffle_button" onclick="run()">
                            <i class="fas fa-stroopwafel"></i>
                            Sortear
                        </button>
                    </div>
                    <div class="well well-lg text-center" id="result">-</div>
                    <div id="winner-form" class="text-center"></div>
                    <small id="register_timer" style="display:none"><span id="register_timer_time">-</span> segundo(s) para registrar</small>
                </div>
            </div>

            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">Sorteados</div>
                </div>
                <div class="panel-body" id="winner-list">

                </div>
            </div>
        </div>
    </div>
{% endblock %}