addon/urls.py
""" Urls dos opcionais """

from django.conf.urls import include, url
from django.views.generic import RedirectView

from addon import views


theme_urls = [
    url(
        r'^(?P<pk>[\d]+)/delete/$',
        views.ThemeDeleteView.as_view(),
        name='theme-delete'
    ),
    url(
        r'^(?P<pk>[\d]+)/edit/$',
        views.ThemeEditView.as_view(),
        name='theme-edit'
    ),
    url(
        r'^add/$',
        views.ThemeAddView.as_view(),
        name='theme-add'
    ),
    url(
        r'^$',
        views.ThemeListView.as_view(),
        name='theme-list'
    ),
]

optional_urls = [
    url(
        r'^products/(?P<optional_pk>[\d]+)/edit/$',
        views.OptionalProductEditView.as_view(),
        name='optional-product-edit'
    ),
    url(
        r'^services/(?P<optional_pk>[\d]+)/edit/$',
        views.OptionalServiceEditView.as_view(),
        name='optional-service-edit'
    ),
    url(
        r'^products/$',
        views.OptionalProductListView.as_view(),
        name='optional-product-list'
    ),
    url(
        r'^services/$',
        views.OptionalServiceListView.as_view(),
        name='optional-service-list'
    ),
    url(
        r'^products/add/$',
        views.OptionalAddProductView.as_view(),
        name='optional-product-add'
    ),
    url(
        r'^services/add/$',
        views.OptionalAddServiceView.as_view(),
        name='optional-service-add'
    ),
    url(
        r'^$',
        RedirectView.as_view(
            pattern_name='addon:optional-service-list',
            permanent=False
        )
    ),
]

urlpatterns = [
    url(r'^events/(?P<event_pk>[\d]+)/addons/', include(optional_urls)),
    url(r'^events/(?P<event_pk>[\d]+)/addons/themes/', include(
        theme_urls
    )),
]

gatheros_event/models/organization.py
# pylint: disable=W5101
"""
Organização é a estrutura máxima da aplicação, pois nela, define-se seus
membros, com seus devidos grupos, e como eles poderão interagir nos eventos
vinculadas a ela.
"""
from datetime import datetime

from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.utils.html import strip_tags

from core.util import model_field_slugify
from gatheros_event.models import Person
from .member import Member
from .mixins import GatherosModelMixin


class Organization(models.Model, GatherosModelMixin):
    CONTA_CORRENTE = 'conta_corrente'
    CONTA_POUPANCA = 'conta_poupanca'
    CONTA_CORRENTE_CONJUNTA = 'conta_corrente_conjunta'
    CONTA_POUPANCA_CONJUNTA = 'conta_poupanca_conjunta'

    BANCO_DO_BRASIL = "001"
    ITAU = "341"
    BRADESCO = "237"
    SANTANDER = "033"
    CAIXA_ECONOMICA = "104"
    BANCOOB = "756"
    SICOOB = "756"
    BANCO_COOPERATIVO_SICREDI = "748"

    ACCOUNT_TYPES = (
        (CONTA_CORRENTE, 'Conta corrente'),
        (CONTA_POUPANCA, 'Conta poupanca'),
        (CONTA_CORRENTE_CONJUNTA, 'Conta corrente conjunta'),
        (CONTA_POUPANCA_CONJUNTA, 'Conta poupanca conjunta'),
    )

    BANK_CODES = (
        (BANCO_DO_BRASIL, 'Banco do Brasil'),
        (ITAU, 'Itau'),
        (BRADESCO, 'Bradesco'),
        (SANTANDER, 'Santander'),
        (CAIXA_ECONOMICA, 'Caixa Economica'),
        (BANCOOB, 'BANCOOB - Banco Cooperativo do Brasil'),
        (SICOOB, 'Sicoob'),
        (BANCO_COOPERATIVO_SICREDI, 'BANCO COOPERATIVO SICREDI S.A.'),
    )

    """ Organização """
    name = models.CharField(max_length=100, verbose_name='nome da organização')
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name='descrição (texto)'
    )
    description_html = models.TextField(
        null=True,
        blank=True,
        verbose_name='descrição (HTML)',
        help_text='Uma descrição com mais recursos textuais para descrever a sua organização.',
    )
    slug = models.SlugField(
        max_length=128,
        blank=True,
        null=True,
        unique=True,
        verbose_name='permalink',
        help_text="Link que aparecerá para exibir as informações da"
                  " organizações: https://gatheros.com/<permalink>"
    )

    avatar_width = models.PositiveIntegerField(null=True, blank=True)
    avatar_height = models.PositiveIntegerField(null=True, blank=True)
    avatar = models.ImageField(
        blank=True,
        null=True,
        width_field='avatar_width',
        height_field='avatar_height',
        verbose_name='foto',
        upload_to='organization',
    )
    website = models.CharField(max_length=255, null=True, blank=True)
    facebook = models.CharField(max_length=255, null=True, blank=True)
    twitter = models.CharField(max_length=255, null=True, blank=True)
    linkedin = models.CharField(max_length=255, null=True, blank=True)
    skype = models.CharField(max_length=255, null=True, blank=True)

    cash_provider = models.CharField(
        max_length=10,
        blank=True,
        null=True,
        verbose_name='provedor de recebimento'
    )
    cash_data = models.CharField(
        max_length=10,
        blank=True,
        null=True,
        verbose_name='dados para recebimento'
    )

    active = models.BooleanField(default=True, verbose_name='ativo')

    internal = models.BooleanField(
        default=True,
        verbose_name='interno'
    )

    # Obrigatório - Código do banco
    bank_code = models.CharField(
        choices=BANK_CODES,
        max_length=3,
        blank=True,
        null=True,
        validators=[RegexValidator(r'^\d{1,10}$')],
        verbose_name='Banco'
    )

    # Obrigatório - Agencia
    agency = models.CharField(
        max_length=5,
        blank=True,
        null=True,
        validators=[RegexValidator(r'^\d{1,10}$')],
        verbose_name='Agencia'
    )

    # Não obrigatório - Dígito verificador da agência
    agencia_dv = models.CharField(
        blank=True,
        null=True,
        max_length=1,
        validators=[RegexValidator(r'^\d{1,10}$')],
        verbose_name='Dígito verificador da agência'
    )

    # Obrigatório - Numero da conta
    account = models.CharField(
        blank=True,
        null=True,
        max_length=13,
        validators=[RegexValidator(r'^\d{1,10}$')],
        verbose_name='Numero da Conta'
    )

    # Não obrigatório - Dígito verificador da Conta
    conta_dv = models.CharField(
        blank=True,
        null=True,
        max_length=2,
        validators=[RegexValidator(r'^\d{1,10}$')],
        verbose_name='Dígito verificador da Conta'
    )

    # Obrigatório - CPF ou CNPJ da conta com ou sem pontuações
    cnpj_ou_cpf = models.CharField(
        max_length=14,
        blank=True,
        null=True,
        verbose_name='CPF ou CNPJ da conta com ou sem pontuações'
    )

    # Obrigatório - Nome completo ou razão social
    legal_name = models.CharField(
        blank=True,
        max_length=30,
        null=True,
        verbose_name='Nome completo ou razão social',
        help_text='IMPORTANTE: este campo não pode ser muito diferente do'
                  ' titular da conta. Se o titular tiver mais de 30'
                  ' caracteres, informe até onde os caracteres.'
    )

    # Obrigatório - Tipo da conta
    account_type = models.CharField(
        choices=ACCOUNT_TYPES,
        default=CONTA_CORRENTE,
        blank=True,
        null=True,
        max_length=25,
        verbose_name='Tipo de Conta'
    )

    bank_account_id = models.IntegerField(
        null=True,
        blank=True,
    )

    document_type = models.CharField(
        max_length=4,
        blank=True,
        null=True,
    )

    date_created = models.CharField(
        max_length=50,
        blank=True,
        null=True,
    )

    # Dados de recebedor do Pagar.me
    active_recipient = models.BooleanField(default=False)

    recipient_id = models.CharField(
        max_length=50,
        null=True,
        blank=True,
    )

    phone = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name='celular',
    )

    email = models.EmailField(
        verbose_name='e-mail',
        null=True,
        blank=True,
    )

    last_access = models.DateTimeField(auto_now=True, blank=True, null=True)

    class Meta:
        verbose_name = 'organização'
        verbose_name_plural = 'organizações'
        ordering = ['name']

        permissions = (
            ("can_invite", "Can invite members"),
            ("can_view", "Can view"),
            ("can_add_event", "Can add event"),
            ("can_view_members", "Can view members"),
            ("can_manage_members", "Can manage members"),
            ("can_manage_places", "Can manage places"),
            ("can_manage_fields", "Can manage form fields"),
        )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        """ Salva entidade. """
        if not self.slug:
            self._create_unique_slug()

        self.description = strip_tags(self.description_html)

        super(Organization, self).save(*args, **kwargs)

    def _create_unique_slug(self):
        self.slug = model_field_slugify(
            model_class=self.__class__,
            instance=self,
            string=self.name
        )

    def get_members(self, group=None, person=None):
        """
        Recupera litsa de membros.

        :param group: string - Filtro de lista por grupo
        :param person: object - filtro de lista por Instância de Person ou User
        :return: QuerySet
        """
        qs = self.members.all()

        if group:
            qs = qs.filter(group=group)

        if person:
            if isinstance(person, User):
                try:
                    person = Person.objects.get(user=person)
                except Person.DoesNotExist:
                    return []

            qs = qs.filter(person=person)
        return qs

    def get_member(self, person):
        """ Recupera Member de organização. """
        members_qs = self.get_members(person=person)
        if len(members_qs) == 0:
            return None

        return members_qs.first()

    def is_member(self, person):
        """
        Verifica se a pessoa ou usuário é membro da organização

        :param person: Pessoa ou usuário que é membro
        :return:
        """
        return len(self.get_members(person=person)) > 0

    def is_admin(self, person):
        """
        Verifica se a pessoa ou usuário é administrador da organização

        :param person: Pessoa ou usuário que é membro
        :return:
        """
        return len(self.get_members(group=Member.ADMIN, person=person)) > 0

    def is_member_active(self, person):
        """ Verifica se membro está ativo na organização. """
        member = self.get_member(person)
        return member.active if member else False

    def is_bank_account_configured(self):
        """ Verifica se possui dados bancários cadastrado no sistema """
        if self.agency and self.account and self.cnpj_ou_cpf \
                and self.legal_name and self.account_type:
            return True

        return False

    def get_invitations(self, include_expired=True, limit=None):
        """
        Recupera convites da organização feita por membros administradores
        """
        invitations = []
        for member in self.members.all():
            invitation_qs = member.invitations
            if not include_expired:
                now = datetime.now()
                invitation_qs = invitation_qs.filter(expired__gte=now)

            if limit:
                invitations += list(invitation_qs.all()[0:int(limit)])
            else:
                invitations += list(invitation_qs.all())

        return invitations

attendance/views/list.py
from django.views.generic import ListView

from attendance.models import AttendanceService
from .mixins import AttendancesFeatureFlagMixin


class ManageListAttendanceView(AttendancesFeatureFlagMixin, ListView):
    model = AttendanceService
    template_name = 'attendance/manage-list-attendance.html'
    ordering = ['name']

    def get_queryset(self):
        query_set = super().get_queryset()
        return query_set.filter(event=self.event).order_by('pk')

    def get_context_data(self, **kwargs):
        # noinspection PyUnresolvedReferences
        context = super().get_context_data(**kwargs)
        context['event'] = self.event
        context['has_inside_bar'] = True
        context['active'] = 'attendance'
        context['attendance_lists'] = AttendanceService.objects.filter(
            event=self.event
        )
        context.update(self.get_event_state_context_data(self.event))
        return context

frontend/templates/organization/cancel-membership.html
{% extends "base/base.html" %}
{% load i18n static %}
{% load organization_tags %}

{% block title %} {{ object.name }} | Congressy{% endblock %}

{% block page_title %}Cancelamento de Participação{% endblock %}
{% block page_sub_title %}{{ object.name }} {% endblock %}
{% block page_description %}Deixar de participar da organização <strong>{{ object.name }}</strong>.{% endblock %}

{% block sidebar %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="well danger-box-message warning">
                <h2>ATENÇÃO!</h2>
                <p>
                    Você tem certeza que desejar sair da organização <strong>{{ object.name }}</strong>?
                </p>
                <p>
                    Isto irá excluir todos os seus dados relacionados a esta organização e você
                    só poderá retornar à mesma se receber um convite de um dos administradores.
                </p>
                <br />
                <form action="{% url 'event:member-manage' member.organization.pk member.pk %}" method="post">
                    {% csrf_token %}
                    <a class="btn btn-danger" href="{% url 'event:organization-panel' object.pk %}">Não, tire-me daqui!</a>
                    <input type="submit" class="btn btn-info" value="Sim, pode prosseguir"/>
                    <input type="hidden" name="action" value="delete" />
                </form>
            </div>

        </div>
    </div>
{% endblock %}

frontend/templates/organization/delete.html
{% extends "base/base.html" %}

{% load static %}{% load i18n static %}
{% load event_tags %}
{% block title %}Excluir organização| Congressy{% endblock %}
{% block page_title %}Excluir organização{% endblock %}
{% block page_sub_title %}{{ organization.name }}{% endblock %}

{% block sidebar %}{% endblock %}
{% block sidebar-bars %}{% endblock %}

{% block content %}


    <div class="row">
        <div class="col-ms-12">
            <div class="panel panel-primary">

                <div class="panel-body">

                    <div style="padding: 5px">
                        Você tem certeza que desejar sair da organização <strong>{{ object.name }}</strong>?
                    </div>
                    <div style="padding: 5px">
                        Isto irá excluir todos os seus dados relacionados a esta organização e você
                        só poderá retornar à mesma se receber um convite de um dos administradores.
                    </div>
                    <br/>
                    <form action=""
                          method="post">{% csrf_token %}
                        <a class="btn btn-default" href="{% url 'event:organization-panel' object.pk %}">Cancelar</a>
                        &nbsp; &nbsp;
                        <input class="btn btn-danger" type="submit" value="Sim, pode prosseguir"/>
                        <input type="hidden" name="action" value="delete"/>
                    </form>

                </div>
            </div>
        </div>
    </div>



{% endblock %}

frontend/templates/organization/financial-form.html
{% extends "base/base.html" %}

{% load static  widget_tweaks organization_tags %}


{% block title %}
    {% if object %}Editar{% else %}Nova{% endif %} Organização | Congressy
{% endblock %}

{% block page_title %}
    {% if object %}Editar{% else %}Nova{% endif %} Organização
{% endblock %}

{% block page_sub_title %}
    {% if object %}
        {{ object.name }} (ID: {{ object.pk }})
    {% endif %}
{% endblock %}

{% block styles %}
    <style type="text/css">
        .django-ckeditor-widget {
            display: block !important;
        }
    </style>

{% endblock %}

{% block sidebar %}{% endblock %}

{% block sidebar-bars %}{% endblock %}

{% block toptitle %}{% endblock %}

{% block content %}
    <form action="" method="post" class="form-horizontal" role="form"
          name="event_form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                <div class="buttonbar">
                    <div class="float-right">
                        {% if next_path %}
                            <a href="{{ next_path|urlencode }}"
                               class="btn btn-danger">
                                <i class="fas fa-times-circle"></i>
                                Cancelar
                            </a>
                            <input type="hidden" name="next"
                                   value="{{ next_path }}"/>
                        {% else %}
                            <a href="{% url 'event:organization-list' %}"
                               class="btn btn-danger">
                                <i class="fas fa-times-circle"></i>
                                Cancelar
                            </a>
                        {% endif %}

                        <button type="submit" class="btn btn-success">
                            <i class="fa fa-save"></i>
                            Salvar
                        </button>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">

                    <div class="panel-body">
                        {% for field in form %}
                            {% if field.field.widget.input_type == "hidden" %}
                                {{ field }}
                            {% else %}
                                <div class="form-group">

                                    <label for="{{ field.id_for_label }}">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <small style="color:#C9302C">*
                                            </small>
                                        {% endif %}
                                    </label>

                                    <div>
                                        {% if field.field.widget.input_type == "checkbox" %}
                                            {{ field |add_class:"js-switch"|attr:"style:display:none" }}
                                        {% else %}
                                            {{ field |add_class:"form-control" }}
                                        {% endif %}
                                        {% if field.errors %}
                                            {% for error in field.errors %}
                                                <div class="alert alert-danger
                                            alert-dismissable">
                                                    <button type="button"
                                                            class="close"
                                                            data-dismiss="alert"
                                                            aria-hidden="true">
                                                        ×
                                                    </button>
                                                    {{ error }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                        {% if field.help_text %}
                                            <div>
                                                <small class="text-muted">{{ field.help_text|safe }}</small>
                                            </div>
                                        {% endif %}
                                    </div>

                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="buttonbar bottom">
                    <div class="float-right">
                        {% if next_path %}
                            <a href="{{ next_path|urlencode }}"
                               class="btn btn-danger">
                                <i class="fas fa-times-circle"></i>Cancelar</a>
                            <input type="hidden" name="next"
                                   value="{{ next_path }}"/>
                        {% else %}
                            <a href="{% url 'event:organization-list' %}"
                               class="btn btn-danger">
                                <i class="fas fa-times-circle"></i>Cancelar</a>
                        {% endif %}

                        <button type="submit" class="btn btn-success">
                            <i class="fa fa-save"></i>
                            Salvar
                        </button>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block scripts %}
    {{ block.super }}

    <!-- mask -->
    <script src="{% static "assets/plugins/mask/mask.min.js" %}"></script>
    <script type="application/javascript">
        $(document).ready(function () {
            $('#id_phone').mask("(99) 99999-9999");
        });
    </script>

    <!-- ckeditor -->
    <script type="text/javascript"
            src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript"
            src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

frontend/templates/organization/list.html
{% extends "base/base.html" %}
{% load static organization_tags %}


{% block sidebar %}{% endblock %}
{% block sidebar-bars %}{% endblock %}

{% block title %}Organizações | Congressy{% endblock %}

{% block page_title %}Organizações{% endblock %}

{% block page_description %}
    Todas as organizações nas quais você é membro.
{% endblock %}

{% block styles %}
    <link rel="stylesheet"
          href="{% static 'assets/plugins/dataTables/css/responsive.bootstrap.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'assets/plugins/dataTables/css/dataTables.css' %}">
    <link rel="stylesheet"
          href="{% static 'assets/plugins/icheck/css/all.css' %}">

{% endblock %}

{% block scripts %}
    <script src="{% static 'assets/plugins/dataTables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/plugins/dataTables/js/dataTables.responsive.min.js' %}"></script>

    <script src="{% static 'assets/plugins/dataTables/js/dataTables.bootstrap.min.js' %}"></script>

    <script src="{% static 'assets/plugins/dataTables/js/responsive.bootstrap.min.js' %}"></script>

    <script>
        $(document).ready(function () {
            $('#organization_table').DataTable({
                "language": {
                    sEmptyTable: "Nenhum registro encontrado",
                    sInfo: "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    sInfoEmpty: "Mostrando 0 até 0 de 0 registros",
                    sInfoFiltered: "(Filtrados de _MAX_ registros)",
                    sInfoPostFix: "",
                    sInfoThousands: ".",
                    sLengthMenu: "_MENU_ resultados por página",
                    sLoadingRecords: "Carregando...",
                    sProcessing: "Processando...",
                    sZeroRecords: "Nenhum registro encontrado",
                    sSearch: "Pesquisar",
                    oPaginate: {
                        sNext: "Próximo",
                        sPrevious: "Anterior",
                        sFirst: "Primeiro",
                        sLast: "Último"
                    },
                    oAria: {
                        sSortAscending: ": Ordenar colunas de forma ascendente",
                        sSortDescending: ": Ordenar colunas de forma descendente"
                    }
                },
                "columnDefs": [
                    // Disable sort in first, last column
                    {
                        "searchable": false,
                        "orderable": false,
                        "width": "3%",
                        "className": "text-center",
                        "targets": [-1]
                    },
                    {
                        "width": "25%",
                        "targets": 1
                    }
                ],
                // Default order
                "order": [[0, 'asc']],
                responsive: true

            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="buttonbar">
                <div class="float-right">
                    <a href="{% url 'event:organization-add' %}" class="btn
                    btn-success">
                        <i class="fa fa-plus"></i>
                        Adicionar
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-body">
                    {% if object_list %}
                        <div class="table col-md-12">
                            <table id="organization_table"
                                   class="table table-striped table-bordered"
                                   cellspacing="0"
                                   width="100%"
                            >
                                <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th></th>
                                    <th>Cargo</th>
                                    <th></th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for item in object_list %}
                                    <tr>
                                        {% get_member_group item user as member_group %}
                                        <td>
                                            <a href="{% url 'event:organization-panel' item.pk %}">{{ item.name }}</a>
                                        </td>
                                        <td style="text-align: center;">
                                            <button type="button"
                                                    class="btn btn-success btn-trans btn-sm dropdown-toggle"
                                                    data-toggle="dropdown"
                                                    aria-expanded="false"
                                                    aria-haspopup="true"
                                                    onclick="cgsy_submit({{ item.pk }})">
                                                <span>Entrar</span>
                                            </button>
                                        </td>
                                        <td>
                                            {% get_member_group_name item user %}
                                        </td>
                                        <td>
                                            {% if member_group == member.ADMIN %}
                                                <div class="btn-group">
                                                    <button
                                                            type="button"
                                                            class="btn
                                                    btn-primary btn-trans
                                                    btn-sm dropdown-toggle"
                                                            data-toggle="dropdown"
                                                            aria-expanded="false"
                                                    >
                                                        <span class="fas fa-cog"></span>
                                                    </button>
                                                    <ul class="dropdown-menu dropdown-menu-right"
                                                        role="menu">
                                                        <li>
                                                            <a href="{% url 'event:organization-edit' item.pk %}">
                                                                <i class="fas fa-pencil-alt"></i>
                                                                Editar
                                                            </a>
                                                        </li>
                                                        {% if item.is_deletable and user has 'gatheros_event.delete_organization' of item %}
                                                            <li>
                                                                <a href="{% url 'event:organization-delete' item.pk %}">
                                                                    <i class="fas fa-trash-alt"></i>
                                                                    Excluir
                                                                </a>
                                                            </li>
                                                        {% endif %}
                                                    </ul>
                                                </div>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <br/>
                            <br/>
                        </div>
                    {% else %}
                        <h3>Nenhum dado.</h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}