addon/urls.py
""" Urls dos opcionais """

from django.conf.urls import include, url
from django.views.generic import RedirectView

from addon import views


theme_urls = [
    url(
        r'^(?P<pk>[\d]+)/delete/$',
        views.ThemeDeleteView.as_view(),
        name='theme-delete'
    ),
    url(
        r'^(?P<pk>[\d]+)/edit/$',
        views.ThemeEditView.as_view(),
        name='theme-edit'
    ),
    url(
        r'^add/$',
        views.ThemeAddView.as_view(),
        name='theme-add'
    ),
    url(
        r'^$',
        views.ThemeListView.as_view(),
        name='theme-list'
    ),
]

optional_urls = [
    url(
        r'^products/(?P<optional_pk>[\d]+)/edit/$',
        views.OptionalProductEditView.as_view(),
        name='optional-product-edit'
    ),
    url(
        r'^services/(?P<optional_pk>[\d]+)/edit/$',
        views.OptionalServiceEditView.as_view(),
        name='optional-service-edit'
    ),
    url(
        r'^products/$',
        views.OptionalProductListView.as_view(),
        name='optional-product-list'
    ),
    url(
        r'^services/$',
        views.OptionalServiceListView.as_view(),
        name='optional-service-list'
    ),
    url(
        r'^products/add/$',
        views.OptionalAddProductView.as_view(),
        name='optional-product-add'
    ),
    url(
        r'^services/add/$',
        views.OptionalAddServiceView.as_view(),
        name='optional-service-add'
    ),
    url(
        r'^$',
        RedirectView.as_view(
            pattern_name='addon:optional-service-list',
            permanent=False
        )
    ),
]

urlpatterns = [
    url(r'^events/(?P<event_pk>[\d]+)/addons/', include(optional_urls)),
    url(r'^events/(?P<event_pk>[\d]+)/addons/themes/', include(
        theme_urls
    )),
]

importer/urls.py
from django.conf.urls import url, include

from importer import views

urls = [
    url(
        r'^csv/(?P<csv_pk>[0-9A-Fa-f-]+)/prepare$',
        views.CSVPrepareView.as_view(),
        name='csv-file-prepare'
    ),
    url(
        r'^csv/(?P<csv_pk>[0-9A-Fa-f-]+)/process$',
        views.CSVProcessView.as_view(),
        name='csv-file-process'
    ),
    url(
        r'^csv/(?P<csv_pk>[0-9A-Fa-f-]+)/delete',
        views.CSVDeleteView.as_view(),
        name='csv-file-delete'
    ),
    url(
        r'^csv/(?P<csv_pk>[0-9A-Fa-f-]+)/cities/',
        views.CSVFixCitiesView.as_view(),
        name='csv-fix-cities'
    ),
    url(
        r'^csv/(?P<csv_pk>[0-9A-Fa-f-]+)/error_file/xls',
        views.CSVErrorXLSView.as_view(),
        name='csv-file-error-xls'
    ),
    url(
        r'^csv/lot/(?P<lot_pk>[\d]+)/example/',
        views.CSVExampleFileView.as_view(),
        name='csv-example-file'
    ),
    url(
        r'^csv/upload$',
        views.CSVFileImportView.as_view(),
        name='csv-file-import'
    ),
    url(
        r'^csv/$',
        views.CSVListView.as_view(),
        name='csv-list'
    ),
]

urlpatterns = [
    url(r'^events/(?P<event_pk>[\d]+)/subscriptions/import/', include(urls)),
]

importer/models/csv_file_config.py
import os
from datetime import datetime
from uuid import uuid4

from django.db import models
from django.utils import timezone

from importer.validators import validate_csv_only_file
from .storage import OverwriteStorage


def get_file_path(instance, *args, **kwargs):
    """ Resgata localização onde os arquivos csv serão salvos. """

    now = datetime.now()
    day = str(now.day)
    month = str(now.month)
    year = str(now.year)
    hour = str(now.hour)
    minute = str(now.minute)

    filename = "Import_Congressy_{}_{}_{}_{}h{}m.csv".format(
        day,
        month,
        year,
        hour,
        minute,
    )

    return os.path.join(
        "event",
        str(instance.event.id),
        "import",
        "csv",
        filename
    )


def get_err_file_path(instance, *args, **kwargs):
    """ Resgata localização onde os arquivos de erro do csv serão salvos. """

    filename = "Import_Congressy.csv"

    return os.path.join(
        "event",
        str(instance.event.id),
        "import",
        "csv",
        "Err_" + str(instance.pk) + '_' + filename
    )


def get_correction_file_path(instance, *args, **kwargs):
    """ Resgata localização onde os arquivos de erro do csv serão salvos. """

    filename = "Import_Congressy_.csv"

    return os.path.join(
        "event",
        str(instance.event.id),
        "import",
        "csv",
        "fix_" + str(instance.pk) + '_' +  filename
    )


class CSVFileConfig(models.Model):
    """
        Representação de todas as configurações de leitura de um arquivo CSV
    """

    ENCODING_UTF8 = "utf-8"
    ENCODING_8859_1 = "iso-8859-1"

    ENCODING_CHOICES = (
        (ENCODING_UTF8, "UTF-8"),
        (ENCODING_8859_1, "ISO 8859-1(Latim)")
    )

    uuid = models.UUIDField(
        default=uuid4,
        editable=False,
        unique=True,
        primary_key=True
    )

    event = models.ForeignKey(
        'gatheros_event.Event',
        on_delete=models.CASCADE,
        verbose_name='evento',
        related_name='csv_file'
    )

    lot = models.ForeignKey(
        'gatheros_subscription.Lot',
        on_delete=models.CASCADE,
        verbose_name='lot',
        related_name='csv_file',
    )

    csv_file = models.FileField(
        upload_to=get_file_path,
        validators=[validate_csv_only_file],
        verbose_name="Arquivo CSV",
    )

    error_csv_file = models.FileField(
        upload_to=get_err_file_path,
        validators=[validate_csv_only_file],
        storage=OverwriteStorage(),
    )

    correction_csv_file = models.FileField(
        upload_to=get_correction_file_path,
        validators=[validate_csv_only_file],
        storage=OverwriteStorage(),
        null=True,
    )

    created = models.DateTimeField(
        verbose_name='criado em',
        editable=False,
    )

    modified = models.DateTimeField(
        verbose_name='modificado em'
    )

    separator = models.CharField(
        max_length=1,
        default='"',
        verbose_name="separador",
    )

    delimiter = models.CharField(
        max_length=1,
        default=",",
        verbose_name="delimitador",
    )

    encoding = models.CharField(
        choices=ENCODING_CHOICES,
        default=ENCODING_UTF8,
        max_length=10,
        verbose_name="tipo de codificação",
    )

    processed = models.BooleanField(
        default=False,
        verbose_name='arquivo já foi processado'
    )

    def save(self, *args, **kwargs):
        if not self.created:
            self.created = timezone.now()

        self.modified = timezone.now()
        return super().save(*args, **kwargs)

    def filename(self):
        return os.path.basename(self.csv_file.name)

    def err_filename(self):
        return os.path.basename(self.error_csv_file.name)

importer/models/storage.py
import os

from django.conf import settings
from django.core.files.storage import FileSystemStorage


class OverwriteStorage(FileSystemStorage):

    def get_available_name(self, name, *args, **kwargs) -> str:
        """Returns a filename that's free on the target storage system, and
        available for new content to be written to.

        Found at: https://stackoverflow.com/questions/9522759/
        imagefield-overwrite-image-file-with-same-name

        Found at http://djangosnippets.org/snippets/976/

        This file storage solves overwrite on upload problem. Another
        proposed solution was to override the save method on the model
        like so (from https://code.djangoproject.com/ticket/11663):

        def save(self, *args, **kwargs):
            try:
                this = MyModelName.objects.get(id=self.id)
                if this.MyImageFieldName != self.MyImageFieldName:
                    this.MyImageFieldName.delete()
            except: pass
            super(MyModelName, self).save(*args, **kwargs)
        """
        # If the filename already exists,
        # remove it as if it was a true file system
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name

importer/forms/csv_city_form.py
from django import forms

from core.forms.widgets import (
    AjaxChoiceField,
)


class CSVCityForm(forms.Form):
    """ Formulário de Person. """

    states = (
        ('', '----'),
            # replace the value '----' with whatever you want, it won't matter
        ("AC", "AC"),
        ("AL", "AL"),
        ("AP", "AP"),
        ("AM", "AM"),
        ("BA", "BA"),
        ("CE", "CE"),
        ("DF", "DF"),
        ("ES", "ES"),
        ("GO", "GO"),
        ("MA", "MA"),
        ("MT", "MT"),
        ("MS", "MS"),
        ("MG", "MG"),
        ("PA", "PA"),
        ("PB", "PB"),
        ("PR", "PR"),
        ("PE", "PE"),
        ("PI", "PI"),
        ("RJ", "RJ"),
        ("RN", "RN"),
        ("RS", "RS"),
        ("RO", "RO"),
        ("RR", "RR"),
        ("SC", "SC"),
        ("SP", "SP"),
        ("SE", "SE"),
        ("TO", "TO"),
    )
    empty = (
        ('', '----'),
    )

    state = forms.ChoiceField(label='Estado', choices=states)
    city = forms.IntegerField(widget=forms.HiddenInput)
    city_name = AjaxChoiceField(label='Cidade', choices=empty)

importer/forms/csv_file_config_form.py
from django import forms

from importer.models import CSVFileConfig


class CSVFileConfigForm(forms.ModelForm):
    event = None

    class Meta:
        model = CSVFileConfig
        fields = [
            'event',
            'separator',
            'delimiter',
            'encoding',
        ]

        widgets = {
            'event': forms.HiddenInput(),
        }

importer/forms/csv_file_form.py
from django import forms

from importer.models import CSVFileConfig
from gatheros_event.models import Event
from gatheros_subscription.models import Lot


class CSVFileForm(forms.ModelForm):
    event = None

    class Meta:
        model = CSVFileConfig
        fields = [
            'event',
            'csv_file',
            'lot',
        ]

        widgets = {
            'event': forms.HiddenInput(),
        }

        labels = {
            'csv_file': 'Arquivo CSV:',
            'lot': 'Escolha um lote para importar as inscrições:',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        initial = kwargs.get('initial')

        if initial:
            event_pk = initial['event']
            self.event = Event.objects.get(pk=event_pk)
            self.fields['lot'].queryset = Lot.objects.filter(
                event=self.event
            )

importer/forms/csv_process_form.py
from django import forms


class CSVProcessForm(forms.Form):
    create_subscriptions = forms.BooleanField(
        widget=forms.HiddenInput,
        required=False,
    )

importer/views/mixins.py
from django.contrib import messages
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from gatheros_subscription.views.subscription import SubscriptionViewMixin
from importer.models import CSVFileConfig


class CSVViewMixin(SubscriptionViewMixin):
    """
        Mixin utilizado para não permitir acesso sem determinada flag ativada.
    """

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)

        if not self.event.feature_configuration.feature_import_via_csv:

            if request.is_ajax():
                message = 'Evento não permite importação via CSV'
                return JsonResponse({'error': message}, status=403)

            else:

                messages.error(request,
                               "Evento não permite importação via CSV.")

                url = reverse_lazy(
                    "subscription:subscription-list",
                    kwargs={
                        'event_pk': self.event.pk
                    }
                )

                return redirect(url)

        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['has_inside_bar'] = True
        context['active'] = 'inscricoes'
        return context


class CSVProcessedViewMixin(CSVViewMixin, generic.DetailView):
    """
        Mixin utilizado para não permitir acesso caso
        arquivo já tenha sido processado.
    """

    object = None

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.event = self.get_event()

        if self.object.processed:
            msg = "Arquivo já processado não pode ser processado novamente"
            messages.error(request, msg)
            return redirect(
                reverse_lazy('importer:csv-list', kwargs={
                    'event_pk': self.event.pk
                })
            )

        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return get_object_or_404(
            CSVFileConfig,
            pk=self.kwargs.get('csv_pk'),
            event=self.kwargs.get('event_pk'),
        )

frontend/templates/importer/csv_process.html
{% extends "base/base.html" %}
{% load i18n static url_tags  form_config_tags %}

{% block title %}Processar importação | Congressy{% endblock %}

{% block page_title %}Processar importação via CSV{% endblock %}
{% block page_sub_title %}{{ event.name }}{% endblock %}
{% block page_description %}
    Processar importação de dados via CSV | {{ object.filename }}
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="buttonbar">
                <div class="float-left">

                    <a href="{% url 'importer:csv-list' event.pk %}"
                       class="btn btn-primary" style="margin-left: 5px">
                        <i class="fas fa-arrow-circle-left"></i>
                        Voltar Lista de arquivos
                    </a>

                    <a href="{% url 'importer:csv-file-prepare' event.pk object.pk %}"
                       class="btn btn-success">
                        <i class="fas fa-pencil-alt"></i>
                        Voltar as configurações
                    </a>

                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12   ">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Inscrições
                    </h3>
                </div>

                <div class="panel-body text-center" id="csv-loader" style="height: 200px; display: none;">

                    <div class="row text-center"
                         style="margin-top:20px;">
                        <h3>Processando arquivo, aguarde...</h3>
                        <i class="fas info-color fa-circle-notch fa-spin
                        fa-6x" style="margin-top: 20px"></i>
                    </div>

                </div>
                <div class="panel-body" id="csv-form-panel">

                    <div class="row">
                        <div class="col-md-12 text-center">
                            <form method="post" id="csv-form">

                                {% csrf_token %}
                                {% render_generic_field form.create_subscriptions %}

                                {% if process_results.valid > 0 and process_results.invalid == 0 %}

                                    <h1>
                                        <strong>Sucesso!</strong> Será possivel gerar <strong>{{ process_results.valid }}</strong> inscrições.
                                    </h1>

                                    <button type="button" class="btn btn-md btn-success generate-success-subscriptions" style="margin-top: 15px">
                                        Gerar inscrições
                                    </button>


                                {% elif process_results.invalid > 0 and process_results.valid == 0 %}

                                    <div class="alert alert-danger">
                                        <strong>Atenção!</strong> Não será possivel gerar nenhuma das {{ process_results.invalid }} linhas no seu arquivo
                                    </div>

                                    <a href="{% url 'importer:csv-file-error-xls' event.pk object.pk %}" class="btn btn-md btn-danger">
                                        Gerar XLS de erros
                                    </a>


                                {% elif process_results.invalid > 0 and process_results.valid > 0 %}


                                    <table class="table" style="width: 30%; margin: 0 auto">

                                        <thead>
                                        <tr>
                                            <th>Quantidade</th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td>{{ process_results.valid }}</td>
                                            <td>
                                                <button type="button" class="btn btn-md btn-success generate-success-subscriptions">
                                                    Gerar inscrições
                                                </button>
                                                <br>
                                                <small class="text-muted warning-color">
                                                    Atenção: Ao girar as inscrições você será redirecionado.
                                                </small>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>{{ process_results.invalid }}</td>
                                            <td>

                                                <a href="{% url 'importer:csv-file-error-xls' event.pk object.pk %}" class="btn btn-md btn-danger">
                                                    Gerar XLS de erros
                                                </a>

                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>



                                {% elif process_results.invalid == 0 and process_results.valid == 0 %}

                                    <div class="alert alert-danger">
                                        <strong>Atenção!</strong>
                                        Não foi possivel gerar nenhuma inscrição do seu arquivo e também não encontramos nenhum erro.
                                        Por gentiliza verifique seu arquivo.
                                    </div>

                                {% endif %}


                            </form>

                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}

    <script type="application/javascript">

        $(document).ready(function () {


            $('.generate-success-subscriptions').on('click', function () {

                $('#csv-form-panel').hide();
                $('#csv-loader').show();

                $('#id_create_subscriptions').val(true);
                $('#id_create_error_xls').val(false);

                $('#csv-form').submit();

            });


        });

    </script>

{% endblock %}

frontend/templates/importer/csv_upload.html
{% extends "base/base.html" %}
{% load  form_config_tags static %}
{% block title %}Importar | Congressy{% endblock %}

{% block page_title %}Importar via CSV{% endblock %}
{% block page_sub_title %}{{ event.name }}{% endblock %}
{% block page_description %}
    Importação de dados via CSV
{% endblock %}

{% block styles %}

    <!-- Select2 lib -->
    <link rel="stylesheet" href="{% static 'assets/plugins/select2/css/select2.min.css' %}">

    <!-- Select2 theme -->
    <link rel="stylesheet" href="{% static 'assets/plugins/select2/css/select2-bootstrap4.min.css' %}">

{% endblock %}

{% block scripts %}

    <!-- Select2 lib -->
    <script src="{% static 'assets/plugins/select2/js/select2.min.js' %}"></script>


    <script type="application/javascript">

        $(document).ready(function () {

            var lot_select_el = $('#id_lot');
            var file_input_el = $('#file-input');
            var download_link = $('#download_link');

            // Starting select2
            lot_select_el.select2({
                theme: "bootstrap4",
                width: 'resolve'
            });

            lot_select_el.on('select2:select', function (e) {
                file_input_el.show();

                var data = e.params.data;
                var event_pk = '{{ event.pk }}';

                var lot_pk = data.id;

                var url = '/manage/events/' + event_pk +
                    '/subscriptions/import/csv/lot/' + lot_pk + '/example/';

                download_link.attr("href", url)


            });


        });

    </script>

{% endblock %}


{% block content %}


    <div class="row">
        <div class="col-md-12">
            <div class="buttonbar">
                <div class="float-left">
                    <a href="{% url 'subscription:subscription-list' event.pk %}"
                       class="btn btn-primary">
                        <i class="fas fa-arrow-circle-left"></i>
                        Voltar
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Upload
                    </h3>
                </div>


                <div class="panel-body">

                    <div class="row">
                        <form method="POST" enctype="multipart/form-data">

                            {% csrf_token %}

                            {{ form.event }}

                            <div id="lot-input">
                                {% render_generic_field form.lot %}
                            </div>


                            <div id="file-input" style="display: none;">

                                <div class="col-md-6">
                                    {% render_generic_field form.csv_file %}

                                    <button type="submit" class="btn btn-success" id="save-submission" style="margin-left: 10px">
                                        Enviar
                                    </button>

                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">

                                        <label for="example_file" style="margin-bottom:0">
                                            Planilha de Exemplo:
                                        </label>

                                        <div style="margin-top: 5px">
                                            <a href="#" class="btn btn-primary" id="download_link">
                                                <i class="fas fa-download"></i>
                                                Download
                                            </a>
                                        </div>
                                        <div>
                                            <small class="text-muted">
                                                Planilha de exemplo para o lote escolhido
                                            </small>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </form>
                    </div>


                </div>


            </div>
        </div>
    </div>


{% endblock %}

frontend/templates/importer/fix_cities.html
{% extends "base/base.html" %}
{% load i18n static url_tags  form_config_tags %}

{% block title %}Processar importação | Congressy{% endblock %}

{% block page_title %}Processar importação via CSV{% endblock %}
{% block page_sub_title %}{{ event.name }}{% endblock %}
{% block page_description %}
    Processar importação de dados via CSV | {{ object.filename }}
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="buttonbar">
                <div class="float-left">

                    <a href="{% url 'importer:csv-list' event.pk %}"
                       class="btn btn-primary" style="margin-left: 5px">
                        <i class="fas fa-arrow-circle-left"></i>
                        Voltar Lista de arquivos
                    </a>

                    <a href="{% url 'importer:csv-file-prepare' event.pk object.pk %}"
                       class="btn btn-success">
                        <i class="fas fa-pencil-alt"></i>
                        Voltar as configurações
                    </a>

                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            {% include 'importer/includes/form_city.html' %}
        </div>
    </div>

{% endblock %}

{% block scripts %}

    <script type="application/javascript">

        $(document).ready(function () {

            window.setTimeout(function () {

                var city_el = $('#id_city_name');

                $('#id_state').change(function () {
                    city_el.html($('<option>').text('Carregando...'));

                    var that = $(this);
                    window.setTimeout(function () {
                        fetch_cities($(that), $('#id_city_name'), $('#id_city'));
                    }, 500);
                });

                city_el.change(function () {
                    $("#id_city").val($(this).val());
                });

            }, 350);

            $('#submit_btn').on('click', function () {

                $('#form-body').hide();
                $('#csv-loader').show();
            });


        });

        function fetch_cities(uf_el, city_list_el, city_hidden_el, selected_value, callback) {
            uf_el = $(uf_el);
            city_list_el = $(city_list_el);
            city_hidden_el = $(city_hidden_el);
            selected_value = selected_value || '';
            callback = callback || null;

            $.ajax({
                url: "/api/cities/?uf=" + $(uf_el).val() + '&length=1000',
                success: function (result) {

                    var listitems = [];
                    var ids = [];

                    $.each(result.results, function (key, value) {
                        listitems.push('<option value=' + value.id + '>' + value.name + '</option>');
                        ids.push(value.id)
                    });

                    city_list_el.html(listitems.join(''));
                    city_list_el.prop('disabled', false);

                    if (selected_value) {
                        window.setTimeout(function () {
                            city_list_el.val(selected_value);
                            city_hidden_el.val(selected_value);
                        }, 500);
                    } else {
                        city_list_el.val(ids[0]);
                        city_hidden_el.val(ids[0]);
                    }

                    if (callback) {
                        callback(result.results)
                    }
                },
                error: function (err) {
                    throw err;
                }
            });
        }

    </script>

{% endblock %}